#!/usr/bin/ruby
require 'yaml'
require 'digest/md5'

conf = YAML::load open(File.dirname(__FILE__)+'/config.yml').read
ssh = conf['ssh']
dir = conf['dir']
url = conf['url']

name = ARGV.shift
exit 1 unless File.exists? name

ext = name.split(/\//).last =~ /^(.*)(\.\w+)$/ ? $2 : ''
hash = Digest::MD5.hexdigest open(name).read

puts cmd = "scp '#{name}' #{ssh}:#{dir}#{hash}#{ext}"
system cmd
puts cmd = "ssh #{ssh} chmod 644 #{dir}#{hash}#{ext}"
system cmd

url = "#{url}#{hash}#{ext}"
puts " => #{url}"
system "echo '#{url}' | pbcopy"
system "open '#{url}'"
